### PR TITLE
SorrTask697_unit_test_update_task_definition 

### PR DESCRIPTION
**Pull request by nehalR777**
Hi @samarth9008 @sonaalKant , 

Requesting a review for the task assigned to me  - https://github.com/sorrentum/sorrentum/issues/697
I had faced an issue as mentioned by @tkpratardan here- https://github.com/sorrentum/sorrentum/issues/705
Details on how we worked around it are also mentioned here - https://github.com/sorrentum/sorrentum/issues/705

### CODE REVIEW

**Comment by samarth9008** [comment]
For now a good thing to understand is why does the GH action test is not running in your PR. Its not an usual behavior.

**Comment by nehalR777** [comment]
@samarth9008 I ran this test case locally and it seemed to be working fine , but i had made some changes in the code https://github.com/sorrentum/sorrentum/issues/705 , facing an issue mocking the AWS credentials , can you help me out here ?

**Comment by samarth9008** [comment]
What help do you need> Whats the issue that you are facing?

**Comment by samarth9008** [comment]
Something wrong with your branch. I am unable to checkout

```
(amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ git pull
Already up to date.
(amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ git checkout "nehalR777:SorrTask697_unit_test_update_task_definition"
error: pathspec 'nehalR777:SorrTask697_unit_test_update_task_definition' did not match any file(s) known to git
(amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ git checkout nehalR777:SorrTask697_unit_test_update_task_definition
error: pathspec 'nehalR777:SorrTask697_unit_test_update_task_definition' did not match any file(s) known to git
(amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ 
```

**Comment by nehalR777** [comment]
@samarth9008, as @11swathi mentioned here https://github.com/sorrentum/sorrentum/issues/696 (`configparser.NoSectionError: No section: 'ck'` )was an issue i was facing this issue too.
I changed `ck`->` __mock__` in the below code.  
https://github.com/sorrentum/sorrentum/blob/e841aaa34c71b200f5405e7257cc108a57086fd8/helpers/haws.py#L140-L143

Running this unit test - https://github.com/sorrentum/sorrentum/pull/706
Worked well for me then 

image

**Comment by samarth9008** [comment]
We cannot change that file. The profile has to be ck over there as it is important for our other workflows. Did you try using mocking approach instead mentioned here

https://github.com/sorrentum/sorrentum/issues/696#issuecomment-1970416504

https://github.com/sorrentum/sorrentum/issues/705#issuecomment-1973356329

**Comment by nehalR777** [comment]
@samarth9008 thank you, was able to mock it as per your suggestion here https://github.com/sorrentum/sorrentum/issues/705#issuecomment-1973356329 , figuring why my test case is failing

**Comment by nehalR777** [comment]
> Something wrong with your branch. I am unable to checkout
> 
> ```
> (amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ git pull
> Already up to date.
> (amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ git checkout "nehalR777:SorrTask697_unit_test_update_task_definition"
> error: pathspec 'nehalR777:SorrTask697_unit_test_update_task_definition' did not match any file(s) known to git
> (amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ git checkout nehalR777:SorrTask697_unit_test_update_task_definition
> error: pathspec 'nehalR777:SorrTask697_unit_test_update_task_definition' did not match any file(s) known to git
> (amp.client_venv) sorrentum@samarthkp:~/src/sorrentum1$ 
> ```

@samarth9008 , hmm interesting , i dont see it as an active branch for the sorrentum repo too

**Comment by nehalR777** [comment]
@samarth9008, I forked the main repository created a branch in my forked repository and then raised a PR from there that could be a possible reason why you are not able to switch to my branch. Could this be a reason why the test cases are failing? 
Can I go ahead and close this PR and create a branch on the main repo, and raise a new PR i hope things will go when then?

**Comment by nehalR777** [comment]
@samarth9008 , closing this PR .

**Pull request closed without merging**
