### PR TITLE
Sorr task522 follow up for pb api

### PR DESCRIPTION
**Pull request by why2000**
#522 and #539 Moved google file apis, reframed it into helper methods instead of a class. Solved some minor bugs.

### CODE REVIEW

**Comment by why2000** [comment]
@gpsaggese Since this PR requires a change to the docker compose builder, it will fail the check (it includes the changes in #566). So we may want to update the docker compose test if this one is to be merged.

**Comment by why2000** [comment]
Refined the get credentials method to cover more situations. Updated the doc following [#539](https://github.com/sorrentum/sorrentum/issues/539#issuecomment-1712357259) and based on the new helper logic.

**Comment by gpsaggese** [comment]
@PomazkinG can you PTAL to this PR?

Besides some nits, we need to:
1) Implement the mechanism to install gspread dynamically (like have a `def install_gspread_if_needed()`).
2) We want to open a port for letting Google authenticate, but we need to do this in the YAML generator of the invoke
- This is something @why2000 can address when he is in cmamp

**Review by gpsaggese — COMMENTED** [review]
Edited a bit, but LG.

**Comment by gpsaggese** [comment]
Can you move this to cmamp? We'll keep working on this there if needed

**Comment by why2000** [comment]
> Can you move this to cmamp? We'll keep working on this there if needed

Will do later today.

**Comment by why2000** [comment]
Now moved, see the cmamp PR above

**Pull request merged**
