### PR TITLE
DevToolsTask550: Fix typo

### PR DESCRIPTION
**Pull request by sonniki**
Fixing a typo that leads to failed assertions.

### CODE REVIEW

**Comment by sonniki** [comment]
> Make sure to do the same PR in cmamp as well.

I thought we could do the same thing as with https://github.com/sorrentum/sorrentum/pull/671: I'll push amp in https://github.com/sorrentum/dev_tools/pull/562 and it will be integrated into cmamp at the next integration. Or will this not work?

**Comment by samarth9008** [comment]
We changed the approach, if applicable any PR done on sorrentum should be mirrored on cmamp. The opposite will be done during integration. So that it will be only one-side integration from cmamp->sorrentum

**Comment by sonniki** [comment]
> We changed the approach, if applicable any PR done on sorrentum should be mirrored on cmamp. The opposite will be done during integration. So that it will be only one-side integration from cmamp->sorrentum

Opened an identical PR in cmamp: https://github.com/cryptokaizen/cmamp/pull/7360
Do you think we can merge the cmamp PR and this one, before https://github.com/sorrentum/dev_tools/pull/562 is reviewed?
Just because reviewing https://github.com/sorrentum/dev_tools/pull/562 might take time while these typo/bug fixing PRs are really straightforward.

**Comment by samarth9008** [comment]
We can merge in `cmamp` before not an issue. After merging in this, make sure to update amp in dev_tools PR so that the amp stays updated in that PR. Not merging rn before GP review's it

**Pull request merged**
