### PR TITLE
Team2 CEX Arbitrage: Created Single df

### PR DESCRIPTION
**Pull request by thejameszhang**
…cation calculations vectorial and therefore much easier

### CODE REVIEW

**Comment by thejameszhang** [comment]
I can make the notebook much more organized and clear, but first let's focus on the content

**Comment by thejameszhang** [comment]
Okay i fixed the issue, sorry for taking so long

**Comment by thejameszhang** [comment]
Does anybody know of a way to preserve the multiindex columns of a dataframe when saving to a csv?

**Comment by thejameszhang** [comment]
note that we don't need cex-arb.ipynb, i just renamed it to be immediate_arb.ipynb for better naming conventions

**Comment by thejameszhang** [comment]
the most updated version of single_df.ipynb is in issue 186, implementing the research paper. i think we can close this one and just review the other one.

**Comment by DanilYachmenev** [comment]
See https://github.com/sorrentum/sorrentum/pull/186#pullrequestreview-1413783823
Also related to this PR as well

**Comment by DanilYachmenev** [comment]
> the most updated version of single_df.ipynb is in issue 186, implementing the research paper. i think we can close this one and just review the other one.

ok, closing this one then

**Pull request closed without merging**
